name: Deploy Frontend to Azure Web App

on:
  workflow_dispatch:
  # Push trigger comentado para evitar deploy automático no primeiro commit
  # Descomente as linhas abaixo se quiser deploy automático em futuros pushes:
  # push:
  #   branches:
  #     - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Create environment files
        working-directory: ./frontend
        run: |
          # Create .env.production for build time
          echo "NEXT_PUBLIC_API_URL=https://expandev-01.azurewebsites.net" > .env.production
          echo "NODE_ENV=production" >> .env.production
          
          # Create .env for runtime
          cp .env.production .env

      - name: npm install, build, and test
        working-directory: ./frontend
        run: |
          npm ci
          npm run build --if-present
          npm run test --if-present -- --passWithNoTests || true

      - name: Prepare deployment package
        run: |
          mkdir -p deployment
          # Copy all frontend files
          cp -r frontend/* deployment/
          cp -r frontend/.next deployment/ 2>/dev/null || true
          cp frontend/.env deployment/ 2>/dev/null || true
          cp frontend/.env.production deployment/ 2>/dev/null || true
          
          cd deployment
          zip -r ../release.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'expandev-02'
          package: .
          startup-command: 'npm start'